// js/mockData.js
export const mockUsers = [
    {
        id: 1,
        serviceName: "Plomería de Emergencia 24/7",
        description: "Servicio profesional de plomería con atención las 24 horas. Reparamos tuberías, instalamos grifos y solucionamos emergencias.",
        price: "Desde $25.000",
        schedule: "24 horas",
        contact: "+56912345678",
        email: "juan.perez@plomeria.com",
        address: "Av. Siempre Viva 123, Santiago",
        category: "Gasfíter",
        rating: 4.8,
        location: { lat: -33.45, lng: -70.66 }
    },
    {
        id: 2,
        serviceName: "Desarrollo de Sitios Web",
        description: "Creación de sitios web modernos y responsivos. Especializado en e-commerce, landing pages y aplicaciones web.",
        price: "Desde $200.000",
        schedule: "Lunes a Viernes",
        contact: "ana.gomez@webdev.cl",
        email: "ana.gomez@webdev.cl",
        address: "Calle Falsa 456, Providencia",
        category: "Programador web",
        rating: 4.5,
        location: { lat: -33.43, lng: -70.61 }
    },
    {
        id: 3,
        serviceName: "Cuidado de Niños Especializado",
        description: "Servicio de niñera profesional con experiencia en cuidado infantil. Referencias verificables y primeros auxilios.",
        price: "Desde $8.000/hora",
        schedule: "Lunes a Sábado",
        contact: "+56987654321",
        email: "carlos.salas@cuidado.org",
        address: "Pasaje Corto 789, Ñuñoa",
        category: "Niñera",
        rating: 4.7,
        location: { lat: -33.46, lng: -70.60 }
    },
    {
        id: 4,
        serviceName: "Muebles de Madera a Medida",
        description: "Fabricación artesanal de muebles en madera maciza. Diseños únicos y personalizados para tu hogar.",
        price: "Desde $150.000",
        schedule: "Lunes a Viernes",
        contact: "beatriz.luna@carpinteria.com",
        email: "beatriz.luna@carpinteria.com",
        address: "Av. Larga 101, Las Condes",
        category: "Carpintero",
        rating: 4.6,
        location: { lat: -33.41, lng: -70.58 }
    },
    {
        id: 5,
        serviceName: "Instalaciones Eléctricas Certificadas",
        description: "Instalaciones eléctricas residenciales y comerciales. Trabajos certificados con garantía de calidad y SEC.",
        price: "Desde $30.000",
        schedule: "Lunes a Sábado",
        contact: "+56911223344",
        email: "roberto.diaz@electricidad.cl",
        address: "Jirón del Medio 212, Maipú",
        category: "Electricista",
        rating: 4.4,
        location: { lat: -33.51, lng: -70.77 }
    },
    {
        id: 6,
        serviceName: "Corte y Peinado Profesional",
        description: "Servicio de peluquería a domicilio. Cortes modernos, tratamientos capilares y peinados para eventos especiales.",
        price: "Desde $15.000",
        schedule: "Lunes a Domingo",
        contact: "+56922334455",
        email: "maria.torres@beauty.cl",
        address: "Av. Providencia 1234, Providencia",
        category: "Peluquero",
        rating: 4.9,
        location: { lat: -33.42, lng: -70.62 }
    },
    {
        id: 7,
        serviceName: "Reparación de Computadores",
        description: "Diagnóstico y reparación de equipos de escritorio y laptops. Instalación de software y recuperación de datos.",
        price: "Desde $20.000",
        schedule: "Lunes a Viernes",
        contact: "+56933445566",
        email: "tech.support@reparaciones.com",
        address: "San Diego 890, Santiago Centro",
        category: "Técnico en computación",
        rating: 4.3,
        location: { lat: -33.44, lng: -70.65 }
    },
    {
        id: 8,
        serviceName: "Mudanzas y Traslados",
        description: "Servicio completo de mudanzas residenciales y comerciales. Embalaje, transporte y montaje incluido.",
        price: "Desde $80.000",
        schedule: "Lunes a Sábado",
        contact: "+56944556677",
        email: "mudanzas.express@transporte.cl",
        address: "Maipú 567, Maipú",
        category: "Servicio de mudanza",
        rating: 4.2,
        location: { lat: -33.52, lng: -70.75 }
    }
];
